name: Fashionit.in
favicon: null
layout_spectrum: 0.5012
typography_spectrum: 0.5
title: 'Indian Vogue '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#49a7c3'
    - '#88d9d0'
    - '#999cd1'
    - '#415fa5'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: null
    url: null
